### ISSUE TITLE
请问这个报错怎么弄？

### ISSUE THREAD

**Issue by MIUXIUS** [mrathena/python.pubg.weapon.auto.recognize.and.suppress#2]
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "pubg.py", line 231, in suppress
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pubg.py", line 245, in <module>
  File "C:\Users\wt\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 49, in _freeze_support
    spawn.spawn_main(**kwds)
  File "multiprocessing\spawn.py", line 120, in spawn_main
  File "multiprocessing\spawn.py", line 133, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by mrathena** [comment]
数组越界了, 子弹数据超过了边界, 可以多加几个数据(比如30个数据后面追加几个), 或者代码里加上边界判断

**Comment by MIUXIUS** [comment]
现在我的情况是  能跑 但是压抢没有效果

**Comment by mrathena** [comment]
1. 用管理员方式运行 pycharm 或 vscode
2. 在游戏外运行 logitech.test.py, 确保能移动鼠标
3. 确保安装的罗技驱动版本正确, 罗技驱动分 LGS (老) 和 GHub (新), LGS 的话, 需要使用 9.02.65 版本的, GHub 的话, 需要使用 2021.11 之前的, 二者自选其一即可. 装好驱动后, 无需重启电脑. 运行 屏蔽GHUB更新.exe 防止更新. 另外需要确保 控制面板-鼠标-指针选项 中下面两个设置
-提高指针精确度 选项去掉, 不然会造成实际移动距离变大
-选择指针移动速度 要在正中间, 靠右会导致实际移动距离过大, 靠左会导致指针移动距离过小

**Comment by MIUXIUS** [comment]
跑 显示

**Comment by MIUXIUS** [comment]
跑 logitech.test.py显示
PS C:\Users\wt\Desktop\python.pubg.weapon.auto.recognize.and.suppress-master>  & 'D:\Program Files (x86)\anacomda\python.exe' 'c:\Users\wt\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '58125' '--' 'c:\Users\wt\Desktop\python.pubg.weapon.auto.recognize.and.suppress-master\logitech.test.py' 
Traceback (most recent call last):
  File "D:\Program Files (x86)\anacomda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files (x86)\anacomda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\wt\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\wt\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\wt\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\wt\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "c:\Users\wt\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 294, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "c:\Users\wt\Desktop\python.pubg.weapon.auto.recognize.and.suppress-master\logitech.test.py", line 5
    from win32gui import GetCursorPosFile "C:\Users\wt\Desktop\python.pubg.weapon.auto.recognize.and.suppress-master\logitech.test.py", line 4, in <module>
                                          ^
SyntaxError: invalid syntax

**Comment by mrathena** [comment]
我更新了下工程, 你照着 readme 把依赖装一下

**Comment by MIUXIUS** [comment]
鼠标还是无法自动下坠
![微信截图_20230101191650](https://user-images.githubusercontent.com/121550520/210168894-8de135f6-8352-486b-931a-768ea0e4e853.png)

**Comment by mrathena** [comment]
要不我加你QQ看一下？你发下QQ吧

**Comment by MIUXIUS** [comment]
qq  854028001 麻烦您了
